/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author louis
 */
public class Catalogue extends javax.swing.JFrame {

    /**
     * Creates new form Catalogue
     */
    public Catalogue() {
        initComponents();

        Connection con = null;

        String url = "jdbc:mysql://localhost:3306/projet?useSSL=false";
        String user = "root";
        String password = "";

        try {
            // create a connection to the database
            con = DriverManager.getConnection(url, user, password);

            //Requete test
            String requete = "Select nom from produit";

            Statement stm = con.createStatement();

            ResultSet resultat = stm.executeQuery(requete);

            while (resultat.next()) {
                jComboBox1.addItem(resultat.getString("nom"));
            }

            con.close();

        } catch (SQLException e) {
            e.printStackTrace();

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1220, 685));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BOUTON MON PANIER .png"))); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(179, 37));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 50, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(255, 102, 102));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 130, 140, -1));

        jComboBox2.setBackground(new java.awt.Color(255, 102, 102));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toutes les catégories", "tulipe", "rose", "Amaryllidacees", "Asteraceae", "armecia", "Liliacees    ", " " }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 130, 140, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BOUTTON RETOUR.png"))); // NOI18N
        jButton3.setPreferredSize(new java.awt.Dimension(93, 35));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 620, -1, -1));

        jPanel2.setBackground(new java.awt.Color(240, 220, 216));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BOUTON AJOUTER AU PANIER.png"))); // NOI18N
        jButton4.setPreferredSize(new java.awt.Dimension(106, 35));
        jButton4.setVerifyInputWhenFocusTarget(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 240, -1, -1));
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 200, 90, 30));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel9.setText("vide");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 130, -1));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 270, 240));

        jLabel11.setText("nom");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 164, -1, 20));

        jLabel12.setText("PrixU");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 184, -1, 20));

        jLabel13.setText("PrixV");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 224, -1, -1));

        jLabel14.setText("QuantitéV");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, 20));

        jTextField5.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 130, 60, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BOUTON CALCULER PRIX.png"))); // NOI18N
        jButton2.setPreferredSize(new java.awt.Dimension(106, 35));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 160, -1, -1));

        jLabel16.setText("€");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 184, 20, 20));

        jLabel17.setText("€");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 224, 30, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CATALOGUE 2 FOND.png"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, 420));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CATALOGUE FOND.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String text = jLabel9.getText();
        //Vérifier si le panier est vide
        if (text.length() == 4) {
            JOptionPane.showMessageDialog(null, "Votre panier est vide !");
        } else {
            Panier panier = new Panier();
            panier.show();
            dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Menu_entree menu = new Menu_entree();
        menu.show();
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    static int nombre_panier_actuel = 0;
    boolean testActionListenerActive = true;

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:

        //System.out.println(testActionListenerActive);
        if (testActionListenerActive) {
            Connection con = null;

            String url = "jdbc:mysql://localhost:3306/projet?useSSL=false";
            String user = "root";
            String password = "";

            try {
                // create a connection to the database
                con = DriverManager.getConnection(url, user, password);

                //System.out.println(jComboBox1.getSelectedIndex());

                if (jComboBox1.getSelectedItem().toString() != null) {
                    String produit = jComboBox1.getSelectedItem().toString();

                    String requete = "Select url_image,nom,prix_unitaire,prix_vrac,quantite_vrac from produit where nom='" + produit + "'";

                    Statement stm = con.createStatement();
                    ResultSet lien = stm.executeQuery(requete);

                    String lien_image = "";
                    String nom = "";
                    String prix_unitaire = "";
                    String prix_vrac = "";
                    String quantite_vrac = "";

                    while (lien.next()) {
                        lien_image = lien.getString("url_image");
                        nom = lien.getString("nom");
                        prix_unitaire = lien.getString("prix_unitaire");
                        prix_vrac = lien.getString("prix_vrac");
                        quantite_vrac = lien.getString("quantite_vrac");

                    }

                    //prix_unitaire += " €";
                    //prix_vrac += " €";
                    jLabel11.setText(nom);
                    jLabel12.setText(prix_unitaire);
                    jLabel13.setText(prix_vrac);
                    jLabel14.setText(quantite_vrac);

                    if (lien_image.length() > 0) {
                        try {

                            jLabel3.setText("");
                            URL image = new URL(lien_image);
                            BufferedImage b = ImageIO.read(image);
                            Image image_recadre = b.getScaledInstance(250, 250, Image.SCALE_DEFAULT);

                            ImageIcon icon = new ImageIcon(image_recadre);
                            jLabel3.setIcon(icon);
                        } catch (MalformedURLException e) {
                            e.printStackTrace();
                        } catch (IOException e) {
                            e.printStackTrace();

                        }
                    } else {
                        jLabel3.setIcon(null);
                    }

                    lien.close();
                    con.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();

            }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        double quantite = Double.parseDouble(jTextField5.getText());
        double total = 0;

        if (Double.parseDouble(jTextField5.getText()) >= Double.parseDouble(jLabel14.getText())) {
            do {
                //jLabel10

                total += (Double.parseDouble(jLabel13.getText()) * (Double.parseDouble(jLabel14.getText())));
                quantite = quantite - (Integer.parseInt(jLabel14.getText()));

            } while (quantite >= Double.parseDouble(jLabel14.getText()));
            total = total + (quantite * Double.parseDouble(jLabel12.getText()));
            jLabel10.setText(String.valueOf(total));
            //System.out.println(total);
        } else {
            total = total + (quantite * Double.parseDouble(jLabel12.getText()));
            jLabel10.setText(String.valueOf(total));
            //System.out.println(total);

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Connection con = null;
        // db parameters
        String url = "jdbc:mysql://localhost:3306/projet?useSSL=false";
        String user = "root";
        String password = "";

        try {
            // create a connection to the database
            con = DriverManager.getConnection(url, user, password);

            String login = membre_login.getTextField();
            String mdp = membre_login.getPasswordField();

            //Requete test
            String requete3 = "Select id_client from acheteur where mail = '" + login + "' and mdp = '" + mdp + "'";
            String requete1 = "Select max(numero_panier) as nouveau_panier, count(id_panier) as nouveau_id from panier";

            Statement stm1 = con.createStatement();
            Statement stm2 = con.createStatement();
            ResultSet resultat = stm1.executeQuery(requete1);
            ResultSet resultat3 = stm2.executeQuery(requete3);

            int id_panier_actuel = 0;
            int id_client = 0;

            while (resultat.next()) {

                nombre_panier_actuel = Integer.parseInt(resultat.getObject(1).toString());
                id_panier_actuel = Integer.parseInt(resultat.getObject(2).toString());

            }

            resultat.close();

            while (resultat3.next()) {
                id_client = Integer.parseInt(resultat3.getObject(1).toString());
            }

            String text = jLabel9.getText();
            //Vérifier si c'est le même panier ou un nouveau avant d'incrémenter
            if (text.length() == 4) {
                nombre_panier_actuel = nombre_panier_actuel + 1;
                jLabel9.setText("plein");
            }

            id_panier_actuel = id_panier_actuel + 1;

            String nom_produit = jLabel11.getText();
            int quantite = Integer.parseInt(jTextField5.getText());
            double Total = Double.parseDouble(jLabel10.getText());

            String requete2 = "Insert into panier values('" + id_panier_actuel + "','" + nombre_panier_actuel + "','" + Total + "','" + quantite + "','" + nom_produit + "','" + id_client + "')";

            Statement stm3 = con.createStatement();
            stm3.executeUpdate(requete2);

            JOptionPane.showMessageDialog(null, "Article ajouté au panier !");

            resultat3.close();
            con.close();

        } catch (SQLException e) {
            e.printStackTrace();

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        Connection con = null;

        String url = "jdbc:mysql://localhost:3306/projet?useSSL=false";
        String user = "root";
        String password = "";

        String categorie = jComboBox2.getSelectedItem().toString();

        if (categorie.equals("Toutes les catégories") == false) {

            try {
                // create a connection to the database
                con = DriverManager.getConnection(url, user, password);

                //Requete test
                String requete = "Select nom from produit where categorie ='" + categorie + "'";

                Statement stm = con.createStatement();

                ResultSet resultat = stm.executeQuery(requete);

                testActionListenerActive = false;

                jComboBox1.removeAllItems();

                //SwingUtilities.invokeLater(() -> testActionListenerActive = false);
                testActionListenerActive = true;

                while (resultat.next()) {
                    jComboBox1.addItem(resultat.getString("nom"));

                }
                con.close();

            } catch (SQLException e) {
                e.printStackTrace();

            }
        } else {

            try {
                con = DriverManager.getConnection(url, user, password);

                //Requete test
                String requete = "Select nom from produit";

                Statement stm = con.createStatement();

                ResultSet resultat = stm.executeQuery(requete);

                testActionListenerActive = false;

                jComboBox1.removeAllItems();

                //SwingUtilities.invokeLater(() -> testActionListenerActive = false);
                testActionListenerActive = true;

                while (resultat.next()) {
                    jComboBox1.addItem(resultat.getString("nom"));

                }
                con.close();

            } catch (SQLException e) {
                e.printStackTrace();

            }
        }

    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Catalogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Catalogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Catalogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Catalogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Catalogue().setVisible(true);
            }
        });
    }

    public static void setLabel(String text) {
        jLabel9.setText(text);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
